version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@1.3.0

parameters:
  build:
    type: boolean
    default: false
  update:
    type: boolean
    default: false

jobs:

  build-docker-image:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            cd GreenApp
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: run lint
          command: |
            cd GreenApp
            . venv/bin/activate
            make lint
      - run:
          name: create docker image
          command: |
            cd GreenApp
            docker build -t greenapp .
            docker image ls
      - run:
          name: test docker image
          command: |
            cd GreenApp
            docker run -d -p 8000:80 greenapp
            if curl http://localhost:8000 | grep 'This'
            then
              echo 'Docker works fine'
            else
              echo 'Docker test failed'
              exit 1
            fi
            
      - run:
          name: upload docker image
          command: |
            cd GreenApp
            docker login -u $docker_username -p $docker_password 
            docker container ls
            docker push svk100/greenapp
            
      - save_cache:
          paths:
          - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}



  build-job:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: echo 'build'

  update-job:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: echo 'update'
  
workflows:
  build-workflow:
    when: << pipeline.parameters.build >>
    jobs:
      - build-docker-image
 
  update-workflow:
    when: << pipeline.parameters.update >>
    jobs:
      - update-job