apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: udacity-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-capstone
  template:
    metadata:
      labels:
        app: udacity-capstone
    spec:
      containers:
      - name: udacity-capstone
        image: svk100/greenapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: default-port